### ISSUE TITLE
How to use this plugin. Merge branches?

### ISSUE THREAD

**Issue by linai081795** [shaharkazaz/vscode-git-merger#1]
How to use this plugin. Merge branches?
I use it for errors

Log output: 
[Error-17:59:14.131] Error while mergning
[Error-17:59:14.131] merge: ' - not something we can merge

**Comment by linai081795** [comment]
[Error-17:59:14.131] Error while mergning
[Error-17:59:14.131] merge: ' - not something we can merge

**Comment by shaharkazaz** [comment]
I found the bug and it should be resolved now, try to update to the latest version.
If it is fixed, please close the issue :)

**Comment by linai081795** [comment]
Thank you for your answer. Yes, bug can not be merged after the update, and thank you for developing the plug-in for vscode
