### ISSUE TITLE
Merge from throws error

### ISSUE THREAD

**Issue by ori007a** [shaharkazaz/vscode-git-merger#15]
## What's this issue all about? 
I tried to use the `merge from` command and I got an error: 

## Logs
[Error-16:49:56] Error while fetching branch list
Unexpected token ' in JSON at position 1

**Comment by shaharkazaz** [comment]
It seems that this happens to windows users, working on it and a fix will be up soon

**Comment by shaharkazaz** [comment]
Fixed 👍
