### ISSUE TITLE
Feature: git merge --continue command

### ISSUE THREAD

**Issue by juninho2410** [shaharkazaz/vscode-git-merger#19]
## What's this issue all about?  
Feature request for adding git merge --continue command.  

I didn't find this in the command list.
I miss the last part of merge process in a conflict resolution that is the --continue command.
Would be nice if this step could be done through the interface click or command(to avoid using terminal).
I don't know if this could be in this plugin or should be in the VS Code editor.
Thanks

**Comment by shaharkazaz** [comment]
I will look into it and see what can be done 👍 Thanks for the feedback

**Comment by shaharkazaz** [comment]
@juninho2410 hopefully this will be done this next week/ 2 weeks 😃

**Comment by juninho2410** [comment]
Wow, really nice!🙂

**Comment by shaharkazaz** [comment]
The dev on this feature is done, now just testing and then releasing it on v0.4.0 🎉

**Comment by shaharkazaz** [comment]
Released! try to use it and update if you have any issues with it! Thanks for the feedback! 🎉

**Comment by juninho2410** [comment]
Ok, thanks!
I'll try to use! :)

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
