### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by linai081795** [shaharkazaz/vscode-git-merger#2]
I found that the merged branch does not synchronize the merged branch of the commit, but when it is submitted to the remote warehouse, the merged commit is displayed

**Comment by shaharkazaz** [comment]
I didn't understand what the problem is can you explain again? 
If you are referring to the fact that after you merge the changes don't auto-commit then this is normal, this is the default behavior of the extension until I add a settings file to it that the user can edit.

**Comment by linai081795** [comment]
When I'm merged, the commit of the merged branch cannot be displayed in time and needs to be submitted again, but when it is submitted again, the commit is displayed again
